### ISSUE TITLE
Close open "add {package}" issues

### ISSUE THREAD

**Issue by ivirshup** [scverse/ecosystem-packages#117]
I think we should close the open "add {package}" issues since we've moved to a submission rather than nomination based model. I do think it could make sense to open issues on the respective repositories asking for them to submit.

Wdyt @grst, @mikelkou?

- [x] #106
- [x] #43 
- [x] #80 
- [x] #40

**Comment by ivirshup** [comment]
@grst did you ask the project to submit as well?

**Comment by grst** [comment]
no, not yet
