### ISSUE TITLE
Maintain a list of GitHub repositories using the cookiecutter template

### ISSUE THREAD

**Issue by flying-sheep** [scverse/ecosystem-packages#87]
We want to find them to give them cruft update PRs. We currently use GH search to find those packages. However, the search has time limits (180 days without commit), so only using it could make us miss repositories.

We should use the scverse bot to maintain the list here to be more flexible: e.g. people can theoretically add the bot as a contributor to their private repo, and we can blocklist entries.

The list should be a human readable file in this repo. (JSON, TOML, or YAML). I’m -1 on JSON because the lack of trailing commas obscures what’s going on in diffs.

**Comment by grst** [comment]
Let's go for yaml, we use this in a lot of other places already. 

This was the search I have been using in my prototype: 
```python
from github import Github
g = Github(os.environ["GITHUB_PAT"])
r = g.search_code(
    "filename:.cruft.json 'https://github.com/scverse/cookiecutter-scverse'"
)
```
